### ISSUE TITLE
Is this project inactive?

### ISSUE THREAD

**Issue by sebasptsch** [aschzero/hera#16]
I'm looking at using this project in my homelab stack but am unsure if it's still actively maintained. It seems that there are issues that haven't had responses and open pull requests that also haven't had activity for a while.

Just wondering if this project is still being actively maintained or if the author, @aschzero is coming back to it at some point.

**Comment by wovalle** [comment]
Hey @sebasptsch, I started working in a similar project at https://github.com/wovalle/angelos. It is on its early stages, missing some features (for example, you need to have a tunnel running) and rough on the edges but it is working in my homelab.

**Comment by sebasptsch** [comment]
Sounds good! Thanks!
